export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_MONSTERS_PENDING = 'REQUEST_MONSTERS_PENDING';
export const REQUEST_MONSTERS_SUCCESS = 'REQUEST_MONSTERS_SUCCESS';
export const REQUEST_MONSTERS_FAILED = 'REQUEST_MONSTERS_FAILED';